# Generated by Django 4.0.1 on 2022-01-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(db_column='NOMBRES', max_length=60)),
                ('apellidos', models.CharField(db_column='APELLIDOS', max_length=60)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', max_length=100, null=True, unique=True)),
                ('last_login', models.DateField(db_column='LAST_LOGIN')),
                ('fechaNacimiento', models.DateField(db_column='FECHA_NACMIENTO')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
