# Generated by Django 4.0.1 on 2022-01-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateField(db_column='LAST_LOGIN', null=True),
        ),
    ]
