# Generated by Django 4.0.1 on 2022-01-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_alter_usuario_fechanacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_active',
            field=models.BooleanField(db_column='IS_ACTIVE', default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_staff',
            field=models.BooleanField(db_column='IS_STAFF', default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_superuser',
            field=models.BooleanField(db_column='IS_SUPERUSER', default=False),
        ),
    ]
