# Generated by Django 4.0.4 on 2022-04-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_usuario_es_active_usuario_es_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombres',
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(db_column='DIRECCION', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fechaCreacion',
            field=models.DateField(db_column='FECHA_REACION', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='primerApellido',
            field=models.CharField(db_column='PRIMER_APELLIDO', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='primerNombre',
            field=models.CharField(db_column='PRIMER_NOMBRE', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='segundoApellido',
            field=models.CharField(db_column='SEGUNDO_APELLIDO', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='segundoNombre',
            field=models.CharField(db_column='SEGUNDO_NOMBRE', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(db_column='SEXO', default='-', max_length=1),
        ),
    ]
