# Generated by Django 4.0.4 on 2022-04-13 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_remove_usuario_apellidos_remove_usuario_nombres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaCreacion',
            field=models.DateTimeField(db_column='FECHA_CREACION', default=django.utils.timezone.now),
        ),
    ]
