# Generated by Django 4.0.4 on 2022-04-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_alter_usuario_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
